creation_rules:
   - azure_keyvault: https://kicwa-keyvault-dev.vault.azure.net/keys/sops-key/436d83ccbce0441e8c5425c2deebdfe3
     encrypted_regex: "(_URL|_TOKEN|_KEY|_CONNECTION_STRING|_USER|_PASSWORD|_PAT)$"