apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: kicwa
spec:
  provider: azure
  secretObjects:
    - secretName: client-id
      type: opaque
      data:
        - objectName: oauth2-proxy-client-id
          key: oauth2_proxy_client_id
    - secretName: client-secret
      type: opaque
      data:
        - objectName: oauth2-proxy-client-secret
          key: oauth2_proxy_client_secret
    - secretName: cookie-secret
      type: opaque
      data:
        - objectName: oauth2-proxy-cookie-secret
          key: oauth2_proxy_cookie_secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "4876d353-f752-4738-ba8c-7415dce4f5cb"
    keyvaultName: "kic-kv"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: oauth2-proxy-client-id
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: oauth2-proxy-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: oauth2-proxy-cookie-secret
          objectType: secret
          objectVersion: ""
    tenantId: "201452c3-8938-4d5f-89f2-0f1098708589" 